version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_HOST: mysqldb
    ports:
      - "3306:3306"
  web:
    restart: always
    build: .
    container_name: nodejs_server
    env_file: ./.env
    environment:
      MYSQL_HOST: mysqldb
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb